// Mock data + i18n + helpers

const STR = {
  pt: {
    appName: 'Work Travel',
    tabTrips: 'Viagens',
    tabCalendar: 'Calendário',
    tabReports: 'Relatórios',
    tabSettings: 'Ajustes',
    upcoming: 'Próximas',
    past: 'Passadas',
    all: 'Todas',
    newTrip: 'Nova viagem',
    nextTrip: 'Próxima viagem',
    inDays: (n) => `em ${n} ${n === 1 ? 'dia' : 'dias'}`,
    today: 'hoje',
    tomorrow: 'amanhã',
    ongoing: 'em andamento',
    daysAgo: (n) => `há ${n} ${n === 1 ? 'dia' : 'dias'}`,
    spent: 'Custo',
    budget: 'Orçamento',
    budgetLeft: 'Restante',
    overBudget: 'Acima do orçamento',
    pending: 'Pendências',
    allSet: 'Tudo pronto',
    itemsPending: (n) => `${n} ${n === 1 ? 'pendência' : 'pendências'}`,
    checklist: 'Pendências',
    flights: 'Voos',
    flightOut: 'Ida',
    flightBack: 'Volta',
    roundTrip: 'Ida e volta',
    total: 'Total',
    lodging: 'Hospedagem',
    lodgingType: 'Tipo',
    lodgingHotel: 'Hotel',
    lodgingAirbnb: 'Airbnb',
    lodgingName: 'Nome do local',
    lodgingAddress: 'Endereço',
    addLodging: 'Adicionar hospedagem',
    editLodging: 'Editar hospedagem',
    noLodgingYet: 'Hospedagem ainda não cadastrada',
    lodgingLater: 'Posso cadastrar depois',
    lodgingPending: 'Pendente — cadastre para não esquecer',
    expenses: 'Custos',
    byCategory: 'Por categoria',
    addExpense: 'Adicionar custo',
    overview: 'Resumo',
    details: 'Detalhes',
    destination: 'Destino',
    dates: 'Datas',
    client: 'Cliente / projeto',
    tripNotes: 'Anotações da viagem',
    tripNotesPlaceholder: 'Ex: levar notebook, reunião às 9h, casaco...',
    // Auth
    signIn: 'Entrar',
    signUp: 'Criar conta',
    welcomeBack: 'Bem-vindo de volta',
    createAccount: 'Crie sua conta',
    welcomeSub: 'Controle suas viagens a trabalho',
    createSub: 'Leva menos de um minuto',
    email: 'E-mail',
    password: 'Senha',
    fullName: 'Nome completo',
    continueWith: 'ou continue com',
    enableFaceId: 'Ativar Face ID',
    enableFaceIdSub: 'Entre rapidamente sem digitar a senha',
    useFaceId: 'Usar Face ID',
    haveAccount: 'Já tem conta?',
    noAccount: 'Ainda não tem conta?',
    forgotPassword: 'Esqueci a senha',
    skip: 'Agora não',
    enable: 'Ativar',
    // Settings
    account: 'Conta',
    editProfile: 'Editar perfil',
    name: 'Nome',
    phone: 'Telefone',
    preferences: 'Preferências',
    dataSync: 'Backup e sincronização',
    cloudBackup: 'Backup na nuvem',
    iCloud: 'iCloud',
    googleDrive: 'Google Drive',
    none: 'Nenhum',
    lastSync: 'Última sincronização',
    syncNow: 'Sincronizar agora',
    syncing: 'Sincronizando...',
    syncedNow: 'agora mesmo',
    security: 'Segurança',
    faceId: 'Face ID',
    changePassword: 'Alterar senha',
    about: 'Sobre',
    version: 'Versão',
    signOut: 'Sair',
    signOutConfirm: 'Deseja realmente sair?',
    changeBackup: 'Escolha onde fazer backup',
    backupOn: 'Ativado',
    backupOff: 'Desativado',
    duration: 'Duração',
    nights: (n) => `${n} ${n === 1 ? 'noite' : 'noites'}`,
    days: (n) => `${n} ${n === 1 ? 'dia' : 'dias'}`,
    save: 'Salvar',
    cancel: 'Cancelar',
    tripName: 'Nome da viagem',
    from: 'De',
    to: 'Para',
    departure: 'Partida',
    return: 'Retorno',
    notes: 'Observações',
    flight: 'Voo',
    hotel: 'Hotel',
    transport: 'Transporte',
    food: 'Alimentação',
    parking: 'Estacionamento',
    carRental: 'Aluguel de carro',
    leisure: 'Lazer',
    other: 'Outros',
    avgDaily: 'Diária média',
    totalSpentYear: 'Total no ano',
    tripsThisYear: 'Viagens este ano',
    exportPdf: 'Exportar PDF',
    reportFor: 'Relatório —',
    settings: 'Ajustes',
    language: 'Idioma',
    theme: 'Tema',
    accentColor: 'Cor de destaque',
    cardStyle: 'Estilo dos cards',
    light: 'Claro',
    dark: 'Escuro',
    currency: 'Moeda',
    monthNames: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
    monthFull: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
    weekdays: ['D','S','T','Q','Q','S','S'],
    monthly: 'Mensal',
    yearly: 'Anual',
    trips: 'viagens',
    trip: 'viagem',
    noTripsMonth: 'Sem viagens neste mês',
    ok: 'OK',
    edit: 'Editar',
    purchased: 'Comprado',
    notPurchased: 'Não comprado',
    booked: 'Reservado',
    notBooked: 'Não reservado',
    confirmationCode: 'Localizador',
    flightNumber: 'Nº do voo',
    seat: 'Assento',
    seat: 'Assento',
    optional: 'opcional',
    paymentTiming: 'Pagamento',
    paidAtBooking: 'Na reserva',
    paidOnSite: 'No dia',
    addToCalendar: 'Adicionar ao calendário',
    addToCalendarSub: 'Criar evento no calendário do iPhone',
    calendar: 'Calendário',
    addingToCalendar: 'Adicionando...',
    addedToCalendar: 'Adicionado ao calendário',
    chooseCalendar: 'Escolher calendário',
    personal: 'Pessoal',
    work: 'Trabalho',
    iCloudCal: 'iCloud',
    includeFlights: 'Incluir voos',
    includeFlightsSub: 'Cria eventos separados para ida e volta',
    alertBefore: 'Alerta',
    atDeparture: 'Na hora',
    min15: '15 min antes',
    hour1: '1 hora antes',
    hour2: '2 horas antes',
    day1: '1 dia antes',
    airline: 'Companhia aérea',
    price: 'Valor',
    totalPrice: 'Valor total',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    address: 'Endereço',
    provider: 'Estabelecimento',
    date: 'Data',
    amount: 'Valor',
    category: 'Categoria',
    description: 'Descrição',
    newExpense: 'Novo custo',
    mostSpentCategory: 'Categoria com maior custo',
    categoryBreakdown: 'Divisão por categoria',
    monthlyAccumulated: 'Acumulado mensal',
    jumpToToday: 'Hoje',
  },
  en: {
    appName: 'Work Travel',
    tabTrips: 'Trips',
    tabCalendar: 'Calendar',
    tabReports: 'Reports',
    tabSettings: 'Settings',
    upcoming: 'Upcoming',
    past: 'Past',
    all: 'All',
    newTrip: 'New trip',
    nextTrip: 'Next trip',
    inDays: (n) => `in ${n} ${n === 1 ? 'day' : 'days'}`,
    today: 'today',
    tomorrow: 'tomorrow',
    ongoing: 'ongoing',
    daysAgo: (n) => `${n} ${n === 1 ? 'day' : 'days'} ago`,
    spent: 'Cost',
    budget: 'Budget',
    budgetLeft: 'Left',
    overBudget: 'Over budget',
    pending: 'Pending',
    allSet: 'All set',
    itemsPending: (n) => `${n} pending`,
    checklist: 'Pending items',
    flights: 'Flights',
    flightOut: 'Outbound',
    flightBack: 'Return',
    roundTrip: 'Round-trip',
    total: 'Total',
    lodging: 'Lodging',
    lodgingType: 'Type',
    lodgingHotel: 'Hotel',
    lodgingAirbnb: 'Airbnb',
    lodgingName: 'Place name',
    lodgingAddress: 'Address',
    addLodging: 'Add lodging',
    editLodging: 'Edit lodging',
    noLodgingYet: 'Lodging not booked yet',
    lodgingLater: 'I\u2019ll add it later',
    lodgingPending: 'Pending \u2014 don\u2019t forget to book',
    expenses: 'Expenses',
    byCategory: 'By category',
    addExpense: 'Add expense',
    overview: 'Overview',
    details: 'Details',
    destination: 'Destination',
    dates: 'Dates',
    client: 'Client / project',
    tripNotes: 'Trip notes',
    tripNotesPlaceholder: 'e.g. bring laptop, 9am meeting, pack a jacket...',
    signIn: 'Sign in',
    signUp: 'Sign up',
    welcomeBack: 'Welcome back',
    createAccount: 'Create your account',
    welcomeSub: 'Track your business travel',
    createSub: 'Takes less than a minute',
    email: 'Email',
    password: 'Password',
    fullName: 'Full name',
    continueWith: 'or continue with',
    enableFaceId: 'Enable Face ID',
    enableFaceIdSub: 'Sign in quickly without typing your password',
    useFaceId: 'Use Face ID',
    haveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    forgotPassword: 'Forgot password',
    skip: 'Not now',
    enable: 'Enable',
    account: 'Account',
    editProfile: 'Edit profile',
    name: 'Name',
    phone: 'Phone',
    preferences: 'Preferences',
    dataSync: 'Backup & sync',
    cloudBackup: 'Cloud backup',
    iCloud: 'iCloud',
    googleDrive: 'Google Drive',
    none: 'None',
    lastSync: 'Last sync',
    syncNow: 'Sync now',
    syncing: 'Syncing...',
    syncedNow: 'just now',
    security: 'Security',
    faceId: 'Face ID',
    changePassword: 'Change password',
    about: 'About',
    version: 'Version',
    signOut: 'Sign out',
    signOutConfirm: 'Are you sure you want to sign out?',
    changeBackup: 'Choose where to back up',
    backupOn: 'Enabled',
    backupOff: 'Disabled',
    duration: 'Duration',
    nights: (n) => `${n} ${n === 1 ? 'night' : 'nights'}`,
    days: (n) => `${n} ${n === 1 ? 'day' : 'days'}`,
    save: 'Save',
    cancel: 'Cancel',
    tripName: 'Trip name',
    from: 'From',
    to: 'To',
    departure: 'Departure',
    return: 'Return',
    notes: 'Notes',
    flight: 'Flight',
    hotel: 'Hotel',
    transport: 'Transport',
    food: 'Food',
    parking: 'Parking',
    carRental: 'Car rental',
    leisure: 'Leisure',
    other: 'Other',
    avgDaily: 'Avg. daily',
    totalSpentYear: 'Total this year',
    tripsThisYear: 'Trips this year',
    exportPdf: 'Export PDF',
    reportFor: 'Report —',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    accentColor: 'Accent color',
    cardStyle: 'Card style',
    light: 'Light',
    dark: 'Dark',
    currency: 'Currency',
    monthNames: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    monthFull: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    weekdays: ['S','M','T','W','T','F','S'],
    monthly: 'Monthly',
    yearly: 'Yearly',
    trips: 'trips',
    trip: 'trip',
    noTripsMonth: 'No trips this month',
    ok: 'OK',
    edit: 'Edit',
    purchased: 'Purchased',
    notPurchased: 'Not purchased',
    booked: 'Booked',
    notBooked: 'Not booked',
    confirmationCode: 'Booking ref.',
    flightNumber: 'Flight no.',
    seat: 'Seat',
    optional: 'optional',
    paymentTiming: 'Payment',
    paidAtBooking: 'At booking',
    paidOnSite: 'On site',
    addToCalendar: 'Add to calendar',
    addToCalendarSub: 'Create event in iPhone Calendar',
    calendar: 'Calendar',
    addingToCalendar: 'Adding...',
    addedToCalendar: 'Added to calendar',
    chooseCalendar: 'Choose calendar',
    personal: 'Personal',
    work: 'Work',
    iCloudCal: 'iCloud',
    includeFlights: 'Include flights',
    includeFlightsSub: 'Create separate events for outbound and return',
    alertBefore: 'Alert',
    atDeparture: 'At time',
    min15: '15 min before',
    hour1: '1 hour before',
    hour2: '2 hours before',
    day1: '1 day before',
    airline: 'Airline',
    price: 'Price',
    totalPrice: 'Total price',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    address: 'Address',
    provider: 'Provider',
    date: 'Date',
    amount: 'Amount',
    category: 'Category',
    description: 'Description',
    newExpense: 'New expense',
    mostSpentCategory: 'Top spending category',
    categoryBreakdown: 'Category breakdown',
    monthlyAccumulated: 'Monthly accumulated',
    jumpToToday: 'Today',
  },
};

// Anchor "today" so the prototype stays consistent
const TODAY = new Date(2026, 3, 19); // Apr 19, 2026

const CATEGORIES = {
  flight:    { key: 'flight',    labelPt: 'Passagem',     labelEn: 'Flight',     color: '#6366F1', glyph: '✈' },
  hotel:     { key: 'hotel',     labelPt: 'Hospedagem',   labelEn: 'Lodging',    color: '#F59E0B', glyph: '⌂' },
  transport: { key: 'transport', labelPt: 'Transporte',   labelEn: 'Transport',  color: '#10B981', glyph: '⛯' },
  food:      { key: 'food',      labelPt: 'Alimentação',  labelEn: 'Food',       color: '#EF4444', glyph: '✦' },
  parking:   { key: 'parking',   labelPt: 'Estacionamento', labelEn: 'Parking',  color: '#64748B', glyph: 'P' },
  carRental: { key: 'carRental', labelPt: 'Aluguel',      labelEn: 'Car rental', color: '#8B5CF6', glyph: '⚙' },
  leisure:   { key: 'leisure',   labelPt: 'Lazer',        labelEn: 'Leisure',    color: '#EC4899', glyph: '✧' },
  other:     { key: 'other',     labelPt: 'Outros',       labelEn: 'Other',      color: '#94A3B8', glyph: '•' },
};

// ── Mock trips ──────────────────────────────────────────
// Year: 2026. Today is April 19. Mix of past / current / future.
const TRIPS = [
  {
    id: 't1',
    name: 'Workshop Design Q1',
    city: 'São Paulo',
    country: 'BR',
    airline: 'LATAM',
    notes: 'Levar notebook e adaptador HDMI. Workshop começa 9h na segunda.',
    start: '2026-02-03',
    end: '2026-02-06',
    budget: 4500,
    currency: 'BRL',
    flightsPrice: 1400,
    checklist: {
      flightOut: { done: true, airline: 'LATAM', code: 'LA3420', booking: 'XPLM42', seat: '8A', currency: 'BRL', time: '2026-02-03T07:10' },
      flightBack: { done: true, airline: 'LATAM', code: 'LA3517', booking: 'XPLM42', seat: '12C', currency: 'BRL', time: '2026-02-06T20:45' },
      lodging: { done: true, kind: 'hotel', name: 'Hotel Fasano Itaim', code: 'HTL-884321', checkIn: '2026-02-03', checkOut: '2026-02-06', price: 2100, currency: 'BRL' },
    },
    expenses: [
      { id: 'e1',  date: '2026-02-03', cat: 'flight',    amount: 1400, desc: 'LATAM LA3420 / LA3517' },
      { id: 'e11', date: '2026-02-03', cat: 'hotel',     amount: 2100, desc: 'Hotel Fasano (3 noites)' },
      { id: 'e2',  date: '2026-02-03', cat: 'transport', amount: 48,   desc: 'Uber GRU → hotel' },
      { id: 'e3',  date: '2026-02-03', cat: 'food',      amount: 62,   desc: 'Jantar' },
      { id: 'e4',  date: '2026-02-04', cat: 'food',      amount: 38,   desc: 'Almoço' },
      { id: 'e5',  date: '2026-02-04', cat: 'food',      amount: 84,   desc: 'Jantar com cliente' },
      { id: 'e6',  date: '2026-02-04', cat: 'transport', amount: 22,   desc: 'Uber' },
      { id: 'e7',  date: '2026-02-05', cat: 'food',      amount: 45,   desc: 'Almoço' },
      { id: 'e8',  date: '2026-02-05', cat: 'food',      amount: 72,   desc: 'Jantar' },
      { id: 'e9',  date: '2026-02-06', cat: 'transport', amount: 55,   desc: 'Uber hotel → GRU' },
    ],
  },
  {
    id: 't2',
    name: 'Reunião Porto Alegre',
    city: 'Porto Alegre',
    country: 'BR',
    airline: 'GOL',
    notes: 'Levar casaco, PoA costuma estar fria em março.',
    start: '2026-03-10',
    end: '2026-03-12',
    budget: 3200,
    currency: 'BRL',
    flightsPrice: 1150,
    checklist: {
      flightOut: { done: true, airline: 'GOL', code: 'G31122', currency: 'BRL', time: '2026-03-10T06:20' },
      flightBack: { done: true, airline: 'GOL', code: 'G31209', currency: 'BRL', time: '2026-03-12T19:00' },
      lodging: { done: true, kind: 'airbnb', name: 'Loft Moinhos de Vento', code: 'HM-44821', checkIn: '2026-03-10', checkOut: '2026-03-12', price: 890, currency: 'BRL' },
    },
    expenses: [
      { id: 'f1', date: '2026-03-10', cat: 'flight',    amount: 1150, desc: 'GOL G31122 / G31209' },
      { id: 'f3', date: '2026-03-10', cat: 'hotel',     amount: 890,  desc: 'Airbnb' },
      { id: 'f2', date: '2026-03-10', cat: 'parking',   amount: 85,   desc: 'Estacionamento GRU' },
      { id: 'f4', date: '2026-03-10', cat: 'food',      amount: 58,   desc: 'Jantar' },
      { id: 'f5', date: '2026-03-11', cat: 'food',      amount: 42,   desc: 'Almoço' },
      { id: 'f6', date: '2026-03-11', cat: 'transport', amount: 35,   desc: 'Uber' },
      { id: 'f7', date: '2026-03-11', cat: 'food',      amount: 64,   desc: 'Jantar' },
      { id: 'f8', date: '2026-03-12', cat: 'food',      amount: 39,   desc: 'Almoço' },
    ],
  },
  {
    id: 't3',
    name: 'Summit Rio',
    city: 'Rio de Janeiro',
    country: 'BR',
    airline: 'Azul',
    notes: 'Summit no Hotel Fairmont. Jantar com time dia 15.',
    start: '2026-04-14',
    end: '2026-04-17',
    budget: 5200,
    currency: 'BRL',
    flightsPrice: 1710,
    checklist: {
      flightOut: { done: true, airline: 'Azul', code: 'AD4010', booking: 'AZFR71', seat: '15F', currency: 'BRL', time: '2026-04-14T09:30' },
      flightBack: { done: true, airline: 'Azul', code: 'AD4115', booking: 'AZFR71', seat: '16A', currency: 'BRL', time: '2026-04-17T18:15' },
      lodging: { done: true, kind: 'hotel', name: 'Hotel Fairmont Copacabana', code: 'FR-772190', checkIn: '2026-04-14', checkOut: '2026-04-17', price: 2850, currency: 'BRL' },
    },
    expenses: [
      { id: 'g1', date: '2026-04-14', cat: 'flight',    amount: 1710, desc: 'Azul AD4010 / AD4115' },
      { id: 'g2', date: '2026-04-14', cat: 'transport', amount: 72,   desc: 'Táxi aeroporto' },
      { id: 'g3', date: '2026-04-14', cat: 'hotel',     amount: 2850, desc: 'Fairmont (3 noites)' },
      { id: 'g4', date: '2026-04-14', cat: 'food',      amount: 95,   desc: 'Jantar' },
      { id: 'g5', date: '2026-04-15', cat: 'food',      amount: 52,   desc: 'Almoço' },
      { id: 'g6', date: '2026-04-15', cat: 'food',      amount: 118,  desc: 'Jantar com cliente' },
      { id: 'g7', date: '2026-04-16', cat: 'food',      amount: 48,   desc: 'Almoço' },
      { id: 'g8', date: '2026-04-16', cat: 'leisure',   amount: 180,  desc: 'Ingresso evento' },
    ],
  },
  {
    id: 't4',
    name: 'Kickoff Belo Horizonte',
    city: 'Belo Horizonte',
    country: 'BR',
    airline: 'LATAM',
    notes: '',
    start: '2026-05-05',
    end: '2026-05-07',
    budget: 3800,
    currency: 'BRL',
    flightsPrice: 1310,
    checklist: {
      flightOut: { done: true, airline: 'LATAM', code: 'LA2210', currency: 'BRL', time: '2026-05-05T08:00' },
      flightBack: { done: true, airline: 'LATAM', code: 'LA2287', currency: 'BRL', time: '2026-05-07T19:30' },
      lodging: { done: true, kind: 'hotel', name: 'Ouro Minas Palace', code: 'OM-33104', checkIn: '2026-05-05', checkOut: '2026-05-07', price: 1400, currency: 'BRL' },
    },
    expenses: [
      { id: 'h1', date: '2026-05-05', cat: 'flight', amount: 1310, desc: 'LATAM LA2210 / LA2287' },
      { id: 'h3', date: '2026-05-05', cat: 'hotel',  amount: 1400, desc: 'Ouro Minas' },
    ],
  },
  {
    id: 't5',
    name: 'Tech Conf NYC',
    city: 'Nova York',
    country: 'US',
    airline: 'LATAM',
    notes: 'Conferência anual, levar passaporte e adaptador de tomada.',
    start: '2026-06-08',
    end: '2026-06-13',
    budget: 18000,
    currency: 'BRL',
    flightsPrice: 8180,
    checklist: {
      flightOut: { done: true, airline: 'LATAM', code: 'LA8181', booking: 'NYZ998', seat: '22D', currency: 'BRL', time: '2026-06-08T22:10' },
      flightBack: { done: true, airline: 'LATAM', code: 'LA8182', booking: 'NYZ998', seat: '22D', currency: 'BRL', time: '2026-06-13T20:30' },
      lodging: { done: false, price: null },
    },
    expenses: [
      { id: 'i1', date: '2026-06-08', cat: 'flight', amount: 8180, desc: 'LATAM LA8181 / LA8182' },
    ],
  },
  {
    id: 't6',
    name: 'Workshop Curitiba',
    city: 'Curitiba',
    country: 'BR',
    airline: 'Azul',
    notes: '',
    start: '2026-07-21',
    end: '2026-07-23',
    budget: 3000,
    currency: 'BRL',
    flightsPrice: 1070,
    checklist: {
      flightOut: { done: true, airline: 'Azul', code: 'AD7701', currency: 'BRL', time: '2026-07-21T07:15' },
      flightBack: { done: true, airline: 'Azul', code: 'AD7784', currency: 'BRL', time: '2026-07-23T18:40' },
      lodging: { done: false, price: null },
    },
    expenses: [],
  },
];

// ── Helpers ─────────────────────────────────────────────
const parseDate = (s) => {
  const [y, m, d] = s.split('-').map(Number);
  return new Date(y, m - 1, d);
};

const fmtMoney = (v, currency = 'BRL') => {
  if (v == null) return '—';
  const abs = Math.abs(v);
  const n = abs >= 1000
    ? abs.toLocaleString('pt-BR', { minimumFractionDigits: 0, maximumFractionDigits: 0 })
    : abs.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const symbol = currency === 'USD' ? 'US$' : 'R$';
  return `${v < 0 ? '-' : ''}${symbol} ${n}`;
};

const fmtMoneyShort = (v, currency = 'BRL') => {
  const symbol = currency === 'USD' ? '$' : 'R$';
  if (v >= 1000) return `${symbol} ${(v / 1000).toFixed(1).replace('.', ',')}k`;
  return `${symbol} ${Math.round(v)}`;
};

const fmtDateShort = (iso, lang = 'pt') => {
  const d = parseDate(iso);
  return `${d.getDate()} ${STR[lang].monthNames[d.getMonth()]}`;
};

const fmtDateRange = (a, b, lang = 'pt') => {
  const da = parseDate(a), db = parseDate(b);
  if (da.getMonth() === db.getMonth()) {
    return `${da.getDate()}–${db.getDate()} ${STR[lang].monthNames[da.getMonth()]}`;
  }
  return `${da.getDate()} ${STR[lang].monthNames[da.getMonth()]} – ${db.getDate()} ${STR[lang].monthNames[db.getMonth()]}`;
};

const daysBetween = (a, b) => Math.round((b - a) / 86400000);

const tripSpent = (t) => t.expenses.reduce((s, e) => s + e.amount, 0);

const tripPending = (t) => {
  const list = [];
  if (!t.checklist.lodging?.done) list.push('lodging');
  return list;
};

const tripStatus = (t, today = TODAY) => {
  const s = parseDate(t.start), e = parseDate(t.end);
  if (today < s) return { state: 'upcoming', days: daysBetween(today, s) };
  if (today > e) return { state: 'past', days: daysBetween(e, today) };
  return { state: 'ongoing', days: 0 };
};

Object.assign(window, {
  STR, TRIPS, CATEGORIES, TODAY,
  parseDate, fmtMoney, fmtMoneyShort, fmtDateShort, fmtDateRange,
  daysBetween, tripSpent, tripPending, tripStatus,
});
